// <auto-generated />
namespace Job_Offers_Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class relationsbetweentables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relationsbetweentables));
        
        string IMigrationMetadata.Id
        {
            get { return "202301261714107_relationsbetweentables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
